//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 04:40:58 PM CEST 
//


package XMLandSecurity.backend1.ws;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lodgings" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "lodgings"
})
@XmlRootElement(name = "getLodgingsRequest")
public class GetLodgingsRequest {

    @XmlElement(required = true)
    protected String lodgings;

    /**
     * Gets the value of the lodgings property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLodgings() {
        return lodgings;
    }

    /**
     * Sets the value of the lodgings property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLodgings(String value) {
        this.lodgings = value;
    }

}
