
package com.project.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LodgingServicePort", targetNamespace = "http://bookingxml.com/soap-example")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LodgingServicePort {


    /**
     * 
     * @param setCompletedLodgingRequest
     * @return
     *     returns com.bookingxml.soap_example.SetCompletedLodgingResponse
     */
    @WebMethod
    @WebResult(name = "setCompletedLodgingResponse", targetNamespace = "http://bookingxml.com/soap-example", partName = "setCompletedLodgingResponse")
    public SetCompletedLodgingResponse setCompletedLodging(
            @WebParam(name = "setCompletedLodgingRequest", targetNamespace = "http://bookingxml.com/soap-example", partName = "setCompletedLodgingRequest")
                    SetCompletedLodgingRequest setCompletedLodgingRequest);

    /**
     * 
     * @param setOccupancyRequest
     * @return
     *     returns com.bookingxml.soap_example.SetOccupancyResponse
     */
    @WebMethod
    @WebResult(name = "setOccupancyResponse", targetNamespace = "http://bookingxml.com/soap-example", partName = "setOccupancyResponse")
    public SetOccupancyResponse setOccupancy(
            @WebParam(name = "setOccupancyRequest", targetNamespace = "http://bookingxml.com/soap-example", partName = "setOccupancyRequest")
                    SetOccupancyRequest setOccupancyRequest);

    /**
     * 
     * @param setLodgingRequest
     * @return
     *     returns com.bookingxml.soap_example.SetLodgingResponse
     */
    @WebMethod
    @WebResult(name = "setLodgingResponse", targetNamespace = "http://bookingxml.com/soap-example", partName = "setLodgingResponse")
    public SetLodgingResponse setLodging(
            @WebParam(name = "setLodgingRequest", targetNamespace = "http://bookingxml.com/soap-example", partName = "setLodgingRequest")
                    SetLodgingRequest setLodgingRequest);

}
