
package com.project.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LodgingServicePort", targetNamespace = "http://bookingxml.com/soap-example")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LodgingServicePort {


    /**
     * 
     * @param getCitiesRequest
     * @return
     *     returns com.bookingxml.soap_example.GetCitiesResponse
     */
    @WebMethod
    @WebResult(name = "getCitiesResponse", targetNamespace = "http://bookingxml.com/soap-example", partName = "getCitiesResponse")
    public GetCitiesResponse getCities(
            @WebParam(name = "getCitiesRequest", targetNamespace = "http://bookingxml.com/soap-example", partName = "getCitiesRequest")
                    GetCitiesRequest getCitiesRequest);

    /**
     * 
     * @param setOccupancyRequest
     * @return
     *     returns com.bookingxml.soap_example.SetOccupancyResponse
     */
    @WebMethod
    @WebResult(name = "setOccupancyResponse", targetNamespace = "http://bookingxml.com/soap-example", partName = "setOccupancyResponse")
    public SetOccupancyResponse setOccupancy(
            @WebParam(name = "setOccupancyRequest", targetNamespace = "http://bookingxml.com/soap-example", partName = "setOccupancyRequest")
                    SetOccupancyRequest setOccupancyRequest);

    /**
     * 
     * @param getLodgingCategoriesRequest
     * @return
     *     returns com.bookingxml.soap_example.GetLodgingCategoriesResponse
     */
    @WebMethod
    @WebResult(name = "getLodgingCategoriesResponse", targetNamespace = "http://bookingxml.com/soap-example", partName = "getLodgingCategoriesResponse")
    public GetLodgingCategoriesResponse getLodgingCategories(
            @WebParam(name = "getLodgingCategoriesRequest", targetNamespace = "http://bookingxml.com/soap-example", partName = "getLodgingCategoriesRequest")
                    GetLodgingCategoriesRequest getLodgingCategoriesRequest);

    /**
     * 
     * @param setCompletedLodgingRequest
     * @return
     *     returns com.bookingxml.soap_example.SetCompletedLodgingResponse
     */
    @WebMethod
    @WebResult(name = "setCompletedLodgingResponse", targetNamespace = "http://bookingxml.com/soap-example", partName = "setCompletedLodgingResponse")
    public SetCompletedLodgingResponse setCompletedLodging(
            @WebParam(name = "setCompletedLodgingRequest", targetNamespace = "http://bookingxml.com/soap-example", partName = "setCompletedLodgingRequest")
                    SetCompletedLodgingRequest setCompletedLodgingRequest);

    /**
     * 
     * @param getAdditionsRequest
     * @return
     *     returns com.bookingxml.soap_example.GetAdditionsResponse
     */
    @WebMethod
    @WebResult(name = "getAdditionsResponse", targetNamespace = "http://bookingxml.com/soap-example", partName = "getAdditionsResponse")
    public GetAdditionsResponse getAdditions(
            @WebParam(name = "getAdditionsRequest", targetNamespace = "http://bookingxml.com/soap-example", partName = "getAdditionsRequest")
                    GetAdditionsRequest getAdditionsRequest);

    /**
     * 
     * @param getLodgingTypesRequest
     * @return
     *     returns com.bookingxml.soap_example.GetLodgingTypesResponse
     */
    @WebMethod
    @WebResult(name = "getLodgingTypesResponse", targetNamespace = "http://bookingxml.com/soap-example", partName = "getLodgingTypesResponse")
    public GetLodgingTypesResponse getLodgingTypes(
            @WebParam(name = "getLodgingTypesRequest", targetNamespace = "http://bookingxml.com/soap-example", partName = "getLodgingTypesRequest")
                    GetLodgingTypesRequest getLodgingTypesRequest);

    /**
     * 
     * @param setLodgingRequest
     * @return
     *     returns com.bookingxml.soap_example.SetLodgingResponse
     */
    @WebMethod
    @WebResult(name = "setLodgingResponse", targetNamespace = "http://bookingxml.com/soap-example", partName = "setLodgingResponse")
    public SetLodgingResponse setLodging(
            @WebParam(name = "setLodgingRequest", targetNamespace = "http://bookingxml.com/soap-example", partName = "setLodgingRequest")
                    SetLodgingRequest setLodgingRequest);

    /**
     * 
     * @param getReservationsRequest
     * @return
     *     returns com.bookingxml.soap_example.GetReservationsResponse
     */
    @WebMethod
    @WebResult(name = "getReservationsResponse", targetNamespace = "http://bookingxml.com/soap-example", partName = "getReservationsResponse")
    public GetReservationsResponse getReservations(
            @WebParam(name = "getReservationsRequest", targetNamespace = "http://bookingxml.com/soap-example", partName = "getReservationsRequest")
                    GetReservationsRequest getReservationsRequest);

}
